=== PyICe-ADI/DC2038A/Python/XML/register_map.dtd
<!ELEMENT register_map (chip+, format_definitions?)>
<!ELEMENT chip (description, address+, command_code*)>
<!ELEMENT address (description?)>
<!ELEMENT command_code (description?, access+, custom_field*, custom_fields*, bit_field+)>
<!ELEMENT access EMPTY>
<!ELEMENT custom_field (#PCDATA)>
<!ELEMENT custom_fields (custom_field*, custom_fields*)>
<!ELEMENT bit_field (description, default?, custom_field*, custom_fields*, preset*, format*)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT default (#PCDATA)>
<!ELEMENT preset (description?)>
<!ELEMENT format EMPTY>
<!ELEMENT format_definitions (constant_definition*, format_definition+)>
<!ELEMENT constant_definition EMPTY>
<!ELEMENT format_definition (description, custom_field*, custom_fields*, transformed_units?, piecewise_linear_points?)>
<!ELEMENT transformed_units (#PCDATA)>
<!ELEMENT piecewise_linear_points (point,point+)>
<!ELEMENT point EMPTY>
<!ATTLIST register_map source_revision CDATA #REQUIRED source_date CDATA #REQUIRED revision CDATA #REQUIRED date CDATA #REQUIRED>
<!ATTLIST chip name CDATA #REQUIRED word_size CDATA #REQUIRED title CDATA #REQUIRED>
<!ATTLIST address address_7bit CDATA #REQUIRED>
<!ATTLIST command_code name ID #REQUIRED value CDATA #REQUIRED>
<!ATTLIST bit_field name ID #REQUIRED size CDATA #REQUIRED offset CDATA #REQUIRED category CDATA #REQUIRED>
<!ATTLIST custom_field name CDATA #REQUIRED value CDATA #IMPLIED>
<!ATTLIST custom_fields name CDATA #REQUIRED value CDATA #IMPLIED>
<!ATTLIST access mode CDATA #REQUIRED type (read | write) #REQUIRED>
<!ATTLIST preset name CDATA #REQUIRED value CDATA #REQUIRED>
<!ATTLIST format name IDREF #REQUIRED>
<!ATTLIST format_definition name ID #REQUIRED signed (True | False | 1 | 0) #REQUIRED>
<!ATTLIST constant_definition name CDATA #REQUIRED value CDATA #REQUIRED>
<!ATTLIST point native CDATA #REQUIRED transformed CDATA #REQUIRED>

=== PyICe-ADI/DC2038A/Python/XML/LTC4162-LADM.xml
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE register_map SYSTEM "register_map.dtd">
<register_map date="$Date: 2018-05-09 10:47:50 -0400 (Wed, 09 May 2018) $" revision="$Revision: $" source_date="Date: 2018-05-09 10:26:00 -0400 (Wed, 09 May 2018)" source_revision="Revision: 1773">
	<chip name="LTC4162" title="Advanced Synchronous Switching Battery Charger and PowerPath Manager" word_size="16">
		<description>The LTC®4162-L is an advanced synchronous switching battery charger and PowerPath manager that seamlessly manages power distribution from input sources such as wall adapters, backplanes, solar panels, etc. and a rechargeable battery. A high resolution telemetry system provides extensive information on circuit voltages, currents, battery resistance and temperatures which can all be read back over the serial interface. The serial interface can also be used to configure many of the charging parameters including termination algorithms as well as numerous system status alerts. The LTC4162-L can charge Lithium-Ion cell stacks as high as eight cells with up to 3.2A of charge current. The power path topology decouples the output voltage from the battery allowing a portable product to start up under very low battery voltage conditions. The LTC4162-L is available in an I²C adjustable version as well as 4.0V, 4.1V and 4.2V fixed voltage versions all with and without MPPT enabled by default. The LTC4162-L is available in the 28-pin 4mm × 5mm × 0.75mm QFN surface mount package.</description>
		<address address_7bit="0x68"/>
		<command_code name="VBAT_LO_ALERT_LIMIT_REG" value="0x01">
			<access mode="user_i2c_mode" type="read"/>
			<access mode="user_i2c_mode" type="write"/>
			<bit_field category="usr_alert_limit" name="vbat_lo_alert_limit" offset="0" size="16">
				<description>Signed number that sets a lower limit that can be used to trigger an interrupt based on the per-cell battery voltage out of range. The value is based on the A/D value, vbat, which has a scaling factor of cell_count × 192.4µV/LSB. To compute the per-cell bit count, divide the desired trigger voltage by both cell_count and 192.4µV. The alert is enabled by setting en_vbat_lo_alert and can be read back and cleared at vbat_lo_alert.</description>
				<default>0</default>
				<format name="vbat_format"/>
			</bit_field>
		</command_code>
		<command_code name="VBAT_HI_ALERT_LIMIT_REG" value="0x02">
			<access mode="user_i2c_mode" type="read"/>
			<access mode="user_i2c_mode" type="write"/>
			<bit_field category="usr_alert_limit" name="vbat_hi_alert_limit" offset="0" size="16">
				<description>Signed number that sets an upper limit that can be used to trigger an interrupt based on the per-cell battery voltage out of range. The value is based on the A/D value, vbat, which has a scaling factor of cell_count × 192.4µV/LSB. To compute the per-cell bit count, divide the desired trigger voltage by both cell_count and 192.4µV. The alert is enabled by setting en_vbat_hi_alert and can be read back and cleared at vbat_hi_alert.</description>
				<default>0</default>
				<format name="vbat_format"/>
			</bit_field>
		</command_code>
		<command_code name="VIN_LO_ALERT_LIMIT_REG" value="0x03">
			<access mode="user_i2c_mode" type="read"/>
			<access mode="user_i2c_mode" type="write"/>
			<bit_field category="usr_alert_limit" name="vin_lo_alert_limit" offset="0" size="16">
				<description>Signed number that sets a lower limit that can be used to trigger an interrupt based on input voltage out of range. The value is based on the A/D value, vin, which has a scaling factor of 1.649mV/LSB. The alert is enabled by setting en_vin_lo_alert and can be read back and cleared at vin_lo_alert.</description>
				<default>0</default>
				<format name="vin_format"/>
			</bit_field>
		</command_code>
		<command_code name="VIN_HI_ALERT_LIMIT_REG" value="0x04">
			<access mode="user_i2c_mode" type="read"/>
			<access mode="user_i2c_mode" type="write"/>
			<bit_field category="usr_alert_limit" name="vin_hi_alert_limit" offset="0" size="16">
				<description>Signed number that sets an upper limit that can be used to trigger an interrupt based on input voltage out of range. The value is based on the A/D value, vin, which has a scaling factor of 1.649mV/LSB. The alert is enabled by setting en_vin_hi_alert and can be read back and cleared at vin_hi_alert.</description>
				<default>0</default>
				<format name="vin_format"/>
			</bit_field>
		</command_code>
		<command_code name="VOUT_LO_ALERT_LIMIT_REG" value="0x05">
			<access mode="user_i2c_mode" type="read"/>
			<access mode="user_i2c_mode" type="write"/>
			<bit_field category="usr_alert_limit" name="vout_lo_alert_limit" offset="0" size="16">
				<description>Signed number that sets a lower limit that can be used to trigger an interrupt based on vout voltage out of range. The value is based on the A/D value, vout, which has a scaling factor of 1.653mV/LSB. The alert is enabled by setting en_vout_lo_alert and can be read back and cleared at vout_lo_alert.</description>
				<default>0</default>
				<format name="vout_format"/>
			</bit_field>
		</command_code>
		<command_code name="VOUT_HI_ALERT_LIMIT_REG" value="0x06">
			<access mode="user_i2c_mode" type="read"/>
			<access mode="user_i2c_mode" type="write"/>
			<bit_field category="usr_alert_limit" name="vout_hi_alert_limit" offset="0" size="16">
				<description>Signed number that sets an upper limit that can be used to trigger an interrupt based on vout voltage out of range. The value is based on the A/D value, vout, which has a scaling factor of 1.653mV/LSB. The alert is enabled by setting en_vout_hi_alert and can be read back and cleared at vout_hi_alert.</description>
				<default>0</default>
				<format name="vout_format"/>
			</bit_field>
		</command_code>
		<command_code name="IIN_HI_ALERT_LIMIT_REG" value="0x07">
			<access mode="user_i2c_mode" type="read"/>
			<access mode="user_i2c_mode" type="write"/>
			<bit_field category="usr_alert_limit" name="iin_hi_alert_limit" offset="0" size="16">
				<description>Signed number that sets an upper limit that can be used to trigger an interrupt based on input current out of range. The value is based on the A/D value, iin, which has a scaling factor of 1.466µV / RSNSI amperes/LSB. The alert is enabled by setting en_iin_hi_alert and can be read back and cleared at iin_hi_alert.</description>
				<default>0</default>
				<format name="iin_format"/>
			</bit_field>
		</command_code>
		<command_code name="IBAT_LO_ALERT_LIMIT_REG" value="0x08">
			<access mode="user_i2c_mode" type="read"/>
			<access mode="user_i2c_mode" type="write"/>
			<bit_field category="usr_alert_limit" name="ibat_lo_alert_limit" offset="0" size="16">
				<description>Signed number that sets a lower limit that can be used to trigger an interrupt based on charge current dropping below a particular value, such as during the constant-voltage phase of charging, or, load current exceeding a particular limit when not charging. When the charger is not running, and telemetry is enabled with force_telemetry_on, this limit indicates that the battery draw has exceeded a particular value. Telemetry will be enabled automatically if the input voltage exceeds the battery voltage, in which case discharge current will be nearly zero. ibat values are positive for charging and negative for discharging so the polarity of this register should be set according to the mode in which the limit alert is of interest. The value is based on the A/D value, ibat, which has a scaling factor of 1.466µV / RSNSB amperes/LSB. The alert is enabled by setting en_ibat_lo_alert and can be read back and cleared at ibat_lo_alert.</description>
				<default>0</default>
				<format name="ibat_format"/>
			</bit_field>
		</command_code>
		<command_code name="DIE_TEMP_HI_ALERT_LIMIT_REG" value="0x09">
			<access mode="user_i2c_mode" type="read"/>
			<access mode="user_i2c_mode" type="write"/>
			<bit_field category="usr_alert_limit" name="die_temp_hi_alert_limit" offset="0" size="16">
				<description>Signed number that sets an upper limit that can be used to trigger an interrupt based on high die temperature. The value in °C can be calculated from the A/D reading, die_temp, as TDIE(°C) = die_temp × 0.0215°C/LSB - 264.4°C. The alert is enabled by setting en_die_temp_hi_alert and can be read back and cleared at die_temp_hi_alert.</description>
				<default>0</default>
				<format name="die_temp_format"/>
			</bit_field>
		</command_code>
		<command_code name="BSR_HI_ALERT_LIMIT_REG" value="0x0A">
			<access mode="user_i2c_mode" type="read"/>
			<access mode="user_i2c_mode" type="write"/>
			<bit_field category="usr_alert_limit" name="bsr_hi_alert_limit" offset="0" size="16">
				<description>Sets an upper limit that can be used to trigger an interrupt based on high battery resistance. The per-cell battery resistance is relative to the battery charge current setting resistor, RSNSB, and can be computed in Ω from: BSR = cell_count × bsr × RSNSB / 500. The alert is enabled by setting en_bsr_hi_alert and can be read back and cleared at bsr_hi_alert.</description>
				<default>0</default>
				<format name="bsr_format"/>
			</bit_field>
		</command_code>
		<command_code name="THERMISTOR_VOLTAGE_HI_ALERT_LIMIT_REG" value="0x0B">
			<access mode="user_i2c_mode" type="read"/>
			<access mode="user_i2c_mode" type="write"/>
			<bit_field category="usr_alert_limit" name="thermistor_voltage_hi_alert_limit" offset="0" size="16">
